name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run tests
        run: |
          go mod download
          go test -v ./... || echo "No tests found or tests failed - continuing with release"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

  terraform-registry:
    needs: goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Notify Terraform Registry
        run: |
          echo "🚀 Release ${{ github.ref_name }} published!"
          echo "Terraform Registry will automatically detect this release."
          echo "Monitor at: https://registry.terraform.io/providers/ploi/ploicloud"